name: Build
on: 
  push:
    branches:
      - master
jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run './build.sh Test Pack'
      run: ./build.sh Test Pack
    - uses: actions/upload-artifact@v1
      with:
        name: test-results
        path: artifacts/test-results
    - uses: actions/upload-artifact@v1
      with:
        name: coverage-report.zip
        path: artifacts/coverage-report.zip
    - uses: actions/upload-artifact@v1
      with:
        name: packages
        path: artifacts/packages